name: React application

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
      - name: Lint with ESLint
        run: |
          npm run lint
      - name: Build the application
        run: |
          npm run build
